// Test output.
void testPrint(const char * const str, ...);

exception ExampleError(int value);

// Entry point.
int testEntryPoint(int argc, char ** argv) {
	try {
		throw ExampleError(1024);
	} catch (ExampleError error) {
		testPrint(C"Caught exception with value %d!", error.value);
	}
	return 0;
}

