Caught base exception with value 3.
