functionThatThrows: Throwing exception.
testEntryPoint: Caught exception with value 8000!
